### ISSUE TITLE
[FEAT] Bug tracking system with GitHub issue

### ISSUE THREAD

**Issue by LouisTsai-Csie** [LouisTsai-Csie/SheetHandler#11]
## Feature Type
Which part contains the error?
- [ ] Data Correctness Check
- [ ] Data Input For Cost Calculation
- [ ] Data Output For Summation Calculation
- [ ] Data Conversion Into Data Sheet
- [ ] Data Collection Template Generator
- [x] Others

## Short Description
A clear and concise description of what you expected to develop.

It is very tedious for teacher to send email when encountering problem, since screen shot and other resource must be prepared. However, the user might not give the detailed information to reproduce the bug, and the efficiency of sending and replying email is low.

One proposed method is to combine GitHub issue generation on the system, if any other problem occurs, they can just type some word and report the issue.

## Additional Information
Add any other expectation about the feature here.

The issue template should follow the existing issue template for consistency.
